select * from customer

-- what is the total revenue generated by male vs female customers

select gender,sum(purchase_amount) as total_revenue
from customer
group by gender;

-- customers who used discount but still spent more than average purchase amount
select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and 
purchase_amount >= (select avg(purchase_amount) from customer);

--top 5 products with highest average review ratings
select item_purchased, round(avg(review_rating)::numeric,2) as avg_review_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--comapre average purchase amount between standard and express shipping type
select shipping_type, avg(purchase_amount)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Do subscribers spend more? compare avg spend and total revenue 
--between subscribers and nonsubcribers
select subscription_status, count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend,
sum(purchase_amount)as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--which 5 products have highest percentage of purchase when discount applied
select item_purchased, 
round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_percent
from customer
group by item_purchased
order by discount_percent desc
limit 5;


---segment customer into new, returning and loyal based on their previous purchase and 
--show the count of each purchase
with customer_type as (
select customer_id, previous_purchases,
case 
     when previous_purchases = 1 then 'New'
     when previous_purchases between 2 and 10 then 'Returning'
	 else 'Loyal'
	 end as customer_segment 
from customer
	
)

select customer_segment, count(*) as no_of_customer
from customer_type
group by customer_segment;

---top 3 most purchased product within each category
with most_purchased_product as(
select category,item_purchased,count(customer_id) as total_orders,
count(item_purchased) over (partition by category order by count(customer_id)) as item_rank
from customer
group by category,item_purchased
)
select category,item_purchased,item_rank from most_purchased_product
where item_rank <=3;

---are repeat customers (previous purchase>5) are also subscribers
select subscription_status,count(customer_id) as repeat_customer
from customer
where previous_purchases>5 
group by subscription_status;

--revenue contribution of each age_group
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;